Been There Done That Workflow

* Introduction

The =btdtwf= package is a mashup of  [[https://software.sandia.gov/trac/pyutilib/browser/pyutilib.workflow][pyutilib.workflow]] and [[http://bbcf.epfl.ch/bein/bein.html][bein]]. 

It uses these packages to allow for constructing of process workflows which also record data and file provenance.  On top of this it adds a caching mechanism which may avoid rerunning a process which has already run on a particular set of input.  

The workflows are constructed out of /processes/ which are the combination of a callable object, its set of input parameters and its set of expected, produced output parameters.   The user does not need to know about =bein= nor =pyutilib.workflow= when writing their callable objects in order to benefit from their features.  The user can construct a workflow which is a mix of =btdtwf= processes and other =pyutilib= tasks.

A framework for constructing task suites is also provided.

* Installation

** Download

#+BEGIN_EXAMPLE
$ git clone https://github.com/brettviren/btdtwf.git
#+END_EXAMPLE

** Install from source

#+BEGIN_EXAMPLE
$ cd btdtwf
$ python setup.py build install
#+END_EXAMPLE

Or

#+BEGIN_EXAMPLE
$ cd btdtwf
$ python setup.py sdist
$ pip install dist/btdtwf-X.Y.Z.tar.gz
#+END_EXAMPLE

* More information

Details on the design and use of =btdtwf= are in  [[doc/btdtwf.org]].

