#+title: Functional Idempotent Predictive Workflow

* COMMENT setup
#+begin_src emacs-lisp :results silent
  (defmacro by-backend (&rest body)
    `(case (if (boundp 'backend) backend nil) ,@body))
#+end_src
 

* Concepts

#+header: :file (by-backend (latex "fipwf.pdf") (t "fipwf.svg"))
#+header: :export results
#+BEGIN_SRC dot
    digraph fipwf {
            label="FIPWF Task";
            result1[shape=circle];
            result2[shape=circle];
            result[shape=circle];
            resultset[shape=octagon];
            paramset[shape=octagon];
            function[shape=diamond];

            result1->resultset;
            result2->resultset;
            param1->paramset;
            param2->paramset;
            resultset->function;
            paramset->function;
            function->result;       
    }
#+END_SRC

#+RESULTS:
[[file:fipwf.svg]]


The Functional Idempotent Predictive Workflow (FIPWF) has objects
which embody the following concepts:

- payload :: the direct output of a /function/
- result :: a /payload/ and its metadata
- result set :: an ordered collection of /results/
- parameter :: a simple, named quantity 
- parameter set :: an ordered collection of /parameters/
- function :: the code run by a task
- task :: an input result set and parameter set, a function and an output result
- signature :: a quantity (hash) representing a result, a result set, a parameter or a parameter set, or a payload
- context :: a collection of the above objects.

Each concept and its attributes are described in the following subsections.

** Signature

A signature is a simple and unique quantity that represents more complex information.  It is typically a hash (eg, SHA1).  Given the complex information, a signature may be computed at any time.  

** Function

A /function/ operates on a /result set/ and a /parameter set/ to produce a /result/.  A function has the following attributes:

- ident :: a human-oriented identifier which may not be unique to all functions
- version :: an identifier that with the /ident/ *should* be unique to all functions
- interface :: a specification of what parameters and results it expects and what result type it produces, by providing these inputs to the /interface/ the output is produced (the function is "called").

** Results

A /result/ embodies the outcome of a function.  A result has the following attributes:

- ident :: a human-oriented identifier which may not be unique to all results
- type :: a descriptor representing the type of payload data this result holds
- payload :: the data of the result which is opaque to FIPWF except that it is null until the function is called.
- function :: the (ident,version) pair of the function that produced it
- signature :: a signature formed from the collection of the /signature/ of the expected /parameter set/  and the /expected signature/ of the expected /result set/ to be passed to the /function/


** Result set

A /result set/ is an ordered collection of results.  It has the following attributes:

- signature :: the signature formed from the collection of the /expected signatures/ of each of its results


** Parameter

A /parameter/ is a quantity simple enough to be provided by a human and which is not produced by a /function/.  It has the following attributes:

- ident :: a human-oriented identifier which may not be unique to all parameters
- type :: a descriptor representing the type of the quantity
- value :: the quantity, which is opaque to FIPWF

** Parameter set

A /parameter set/ is an ordered collection of /parameters/.  It has the following attributes:

- signature :: a signature computed on the attributes of the parameters in the set.

** Functional, Predictable, Idempotent and Cheating

FIPWF is /functional/ in that the results at all scale depend only on the input and the functions.  Rerunning the same /function/ on the same input always produces the same /result/.  It is /predictable/ in that one can describe what functions to call on what inputs before that input is available.  It is /idempotent/ because it is functional.  Once a function is called it need not be called again on the same inputs.

However, FIPWF can only live up to these descriptors if there is not cheating.  In particular, if a function is modified and does not have associated a novel version then two calls to the "same" function with truly the same inputs can produce differing results.  Likewise, if any parameters or input results are introduced to a function through some mechanism other than its /parameter set/ and /result set/ then subsequent "identical" calls may produce different results.  When the mechanism to assert idempotency is put in place such "cheating" will result in undefined behavior.

** More Objects

These are for bookkeeping object types.

- =sig()= :: an operator taking an object and returning a signature
- =Fsig= :: a signature of a /function/ =sig(name,version)=
- =Psig= :: a signature of a /parameter set/ =sig(ps)=
- =RSspec= :: a specification of a result set =tuple(Rsig1, Rsig2, ..., RsigN)=
- =Tspec= :: a specification of a task =tuple(Fsig, RSspec, Psig)=
- =Rsig= :: a signature of result coming from a task =sig(Tspec)=

Note, the values of these objects do not depend on executing a /function/.

** Operations 

The FIPWF needs the following operations

- calculate signatures for /parameter sets/, /results/ and /result sets/.  
- look up a result based on a human-oriented query
- determine if result has been calculated
- assemble task to calculate it
- look up parametersets and resultsets based on signatures
- calling a /function/ and receive and store the result.
- resolve dependencies if a result is required, its function must be located and called
- associate human-oriented names to results, result sets, parameter sets, functions

** Context

The FIPWF /context/ is a database (relational or otherwise) that collects the objects and attributes described above and allows for the needed operations to be performed.  Any guarantees of uniqueness (such as the /signatures/) are made up to only the scope of the context.



